class MarkAbsentJob < ApplicationJob
  queue_as :default

  def perform
    organization = Organization.first
    Current.organization = organization

    today         = Date.today
    working_days  = organization.settings["working_days"] || [1, 2, 3, 4, 5]

    return unless working_days.include?(today.wday)

    return if OrganizationHoliday.where(date: today).exists?

    active_employees = Employee.where(employment_status: :active)

    active_employees.each do |employee|
      next if AttendanceRecord.where(employee: employee, date: today).exists?

      on_leave = LeaveRequest.where(
        employee: employee,
        status:   :approved
      ).where(
        "start_date <= ? AND end_date >= ?", today, today
      ).exists?

      next if on_leave

      AttendanceRecord.create!(
        employee:     employee,
        date:         today,
        status:       :absent,
        organization: organization,
        notes:        "Auto-generated by nightly job"
      )
    end

    Rails.logger.info "MarkAbsentJob completed for #{today}"
  end
end